# ----------- CONFIGURABLE START -----------
title:            "胖蒜"
description:      "致力于分享新鲜有趣知识。"
url:              https://pangsuan.com # 域名
signoff:          "mhcyong" # Your name
facebook_appid:   #liberxue
google_analytics: UA-101222464-1
share:            true 
# 分页
paginate: 12
paginate_path: "page:num"
gems: [jekyll-paginate]
links:
  - name:         首页
    url:          /
    external:     false
  - name:         博客
    url:          https://blog.pangsuan.com
    external:     true
  - name:         搜索
    url:          /search.html
    external:     false
  - name:         归档
    url:          /archives
    external:     false
  - name:         标签
    url:          /tags
    external:     false
  - name:         关于
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
