# is a organization repository
organization: false

# site title
title: Blog

# github user
user: mhcyong

# issue repository
repository: blog

# multi-author
authors:

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 8#d2a17cecee797f60e358c52c619a3978f49ce3c

# posts per page
perpage: 7

order: CREATED_AT

ignores: "17,13"
